//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Индивидуальный_Проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugReport
    {
        public int BugID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Tema { get; set; }
        public string Opisanie { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<bool> IsFixed { get; set; }
    }
}
