//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Индивидуальный_Проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korzina
    {
        public int KorzinaID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TovarID { get; set; }
        public Nullable<int> Kolichestvo { get; set; }
        public Nullable<int> ObshchayaStoimostt { get; set; }
    }
}
