//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Индивидуальный_Проект
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovari
    {
        public int TovarID { get; set; }
        public string NazvanieTovara { get; set; }
        public string Opisanie { get; set; }
        public Nullable<int> Stoimostt { get; set; }
        public byte[] Izobrazhenie { get; set; }
        public Nullable<int> ShowType { get; set; }
        public Nullable<int> Creator { get; set; }
    }
}
