//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Индивидуальный_Проект
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MDZEntities : DbContext
    {
        public MDZEntities()
            : base("name=MDZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tovari> Tovari { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Korzina> Korzina { get; set; }
        public virtual DbSet<BugReport> BugReport { get; set; }
    }
}
